# Generated by Django 2.1.1 on 2018-11-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwirek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
